// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: LoadTester

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_Main
void ui_Main_screen_init(void);
lv_obj_t *ui_Main;
lv_obj_t *ui_MeasurementDock;
lv_obj_t *ui_MeasurementCondition;
lv_obj_t *ui_MeasurementVoltage;
lv_obj_t *ui_MeasurementValue;
lv_obj_t *ui_MeasurementUNIT;
lv_obj_t *ui_VoltageChart;
lv_obj_t *ui_FunctionDocke;
lv_obj_t *ui_Function;
lv_obj_t *ui_ColorFix;
void ui_event_ContMode( lv_event_t * e);
lv_obj_t *ui_ContMode;
lv_obj_t *ui_TextContMode;
void ui_event_LCRMode( lv_event_t * e);
lv_obj_t *ui_LCRMode;
lv_obj_t *ui_TextLCRMode;
void ui_event_LoadMode( lv_event_t * e);
lv_obj_t *ui_LoadMode;
lv_obj_t *ui_TextLoadMode;
void ui_event_LineMode( lv_event_t * e);
lv_obj_t *ui_LineMode;
lv_obj_t *ui_TextLineMode;
lv_obj_t *ui_ImageSerial;
lv_obj_t *ui_SerialStatus;
void ui_event_RUNSTOP( lv_event_t * e);
lv_obj_t *ui_RUNSTOP;
lv_obj_t *ui_TextIRUNSTOP;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_Main_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_Main);
}
