// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: LoadTester

#ifndef _LOADTESTER_UI_H
#define _LOADTESTER_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Main
void ui_Main_screen_init(void);
extern lv_obj_t *ui_Main;
extern lv_obj_t *ui_MeasurementDock;
extern lv_obj_t *ui_MeasurementCondition;
extern lv_obj_t *ui_MeasurementVoltage;
extern lv_obj_t *ui_MeasurementValue;
extern lv_obj_t *ui_MeasurementUNIT;
extern lv_obj_t *ui_VoltageChart;
void ui_event_SinductorCalib( lv_event_t * e);
extern lv_obj_t *ui_SinductorCalib;
extern lv_obj_t *ui_FunctionDocke;
extern lv_obj_t *ui_Function;
extern lv_obj_t *ui_ColorFix;
void ui_event_ContMode( lv_event_t * e);
extern lv_obj_t *ui_ContMode;
extern lv_obj_t *ui_TextContMode;
void ui_event_LCRMode( lv_event_t * e);
extern lv_obj_t *ui_LCRMode;
extern lv_obj_t *ui_TextLCRMode;
void ui_event_LoadMode( lv_event_t * e);
extern lv_obj_t *ui_LoadMode;
extern lv_obj_t *ui_TextLoadMode;
void ui_event_LineMode( lv_event_t * e);
extern lv_obj_t *ui_LineMode;
extern lv_obj_t *ui_TextLineMode;
extern lv_obj_t *ui_ImageSerial;
extern lv_obj_t *ui_SerialStatus;
void ui_event_RUNSTOP( lv_event_t * e);
extern lv_obj_t *ui_RUNSTOP;
extern lv_obj_t *ui_TextIRUNSTOP;
// CUSTOM VARIABLES

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_281677161);   // assets/tabler_plug-connected-x .png
LV_IMG_DECLARE( ui_img_1403710832);   // assets/icons8-audio-wave-32.png
LV_IMG_DECLARE( ui_img_1082144145);   // assets/icons8-sine-32.png
LV_IMG_DECLARE( ui_img_lucide_plug_png);   // assets/lucide_plug.png
LV_IMG_DECLARE( ui_img_2018925606);   // assets/tabler_plug-connected .png

// FONTS
LV_FONT_DECLARE( ui_font_ASCII18);
LV_FONT_DECLARE( ui_font_ASCII48);
LV_FONT_DECLARE( ui_font_ASCII72);
LV_FONT_DECLARE( ui_font_CHN16);
LV_FONT_DECLARE( ui_font_CHN18);
LV_FONT_DECLARE( ui_font_CHN24);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
